server:
  port: 8010
spring:
  application:
    name: account
  datasource:
    name: orderingsystem
    url: jdbc:mysql://101.200.169.159:3306/orderingsystem?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.southwind.entity
